#!/bin/bash
set -euo pipefail
# Debug
set -x

target="${1:-}"

# Create the firebae config file based on type of deploy
if [[ "$target" != "production" ]] && [[ "$target" != "staging" ]]; then
    echo "Usage: ./$(basename "$0") <environment>" >&2
    echo "environment $target was not understood" >&2
    exit 1
fi

if [[ "$target" == "production" ]]; then
    project="archform-1"
    site_name="feed-prod"
    env_file=".env.live"
    export_command="export:production"
else
    project="archform-1-dev"
    site_name="scaler-staging"
    env_file=".env.staging"
    export_command="export:staging"
fi

sed "s/{{ site_name }}/$site_name/g" firebase.default.json > firebase.json

cp "$env_file" .env.production

# Build the site
yarn "$export_command"

# Restore the backup
if [[ -f .env.bak ]]; then
    rm -f .env
    mv .env.bak .env
fi

# Configure deplopy target
firebase use "$project"

# Deploy
firebase deploy --only=hosting
